# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache: pip
# build matrix: different python and pandoc versions
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
  # pypy (version info from [Changelogs — PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"  # PyPy2.7 5.3.1 (CPython 2.7 compatible)
  - "pypy3" # PyPy3 2.4.0 (CPython 3.2 compatible)
# https://groups.google.com/forum/?fromgroups#!topic/pandoc-discuss/uGASAhRydfI
env:
  - pandocVersion=1.17.2-1
  - pandocVersion=1.18-1
matrix:
  allow_failures:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "nightly"
    - python: "pypy"
    - python: "pypy3"
  fast_finish: true
# command to install dependencies
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/${pandocVersion%-*}/pandoc-$pandocVersion-amd64.deb &&
    sudo dpkg -i pandoc-$pandocVersion-amd64.deb
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
install: "python setup.py install"
# pasteurize
before_script: pasteurize -wnj 8 .
# command to run tests
script: py.test -vv --cov=panflute tests
after_script:
  - pip install .
  - find . -iname '*.md' -print0 | xargs -0 -i -n1 -P4 bash -c 'pandoc -t native -F panflute $0' {}
deploy:
  provider: pypi
  user: sergiocorreia
  password: $pypi_password
  skip_cleanup: true
  on:
    python: "3.5"
    condition: $pandocVersion = 1.18-1
